server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  #rabbitmq配置
  rabbitmq:
    host: 192.168.36.132
    port: 5672
    username: admin
    password: mypass
    virtual-host: /
    publisher-confirms: true   #开启发送确认
    publisher-returns: true  #开启发送失败回退
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
        
# log
logging:
  level:
    root: com.kang.mapper:INFO
    
